steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fitness-edge:${SHORT_SHA}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fitness-edge']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'fitness-edge', '--image', 'gcr.io/$PROJECT_ID/fitness-edge:${SHORT_SHA}', '--region', 'asia-northeast1', '--allow-unauthenticated', '--platform',  'managed' ]
  
images:
- gcr.io/$PROJECT_ID/fitness-edge